openapi: '3.0.2'

info:
  title: Lookforward API
  version: '1.0'

servers:
  - url: https://api.lookforward.test/v1

tags:
  - name: Calendarific
  - name: Lookforward

components:
  schemas:
    CountryResponse:
      required: 
        - "meta"
        - "response"
      properties: 
        meta: 
          required: 
            - "code"
          properties: 
            code: 
              type: "number"
          type: "object"
        response: 
          required: 
            - "url"
            - "countries"
          properties: 
            url: 
              type: "string"
            countries: 
              type: "array"
              items: 
                type: "object"
                properties: 
                  country_name: 
                    type: "string"
                  iso-3166: 
                    type: "string"
                  total_holidays: 
                    type: "number"
                  supported_languages: 
                    type: "number"
                  uuid: 
                    type: "string"
          type: "object"

    HolidayResponse:
      required: 
        - "meta"
        - "response"
      properties: 
        meta: 
          required: 
            - "code"
          properties: 
            code: 
              type: "number"
          type: "object"
        response: 
          required: 
            - "holidays"
          properties: 
            holidays: 
              type: "array"
              items: 
                type: "object"
                properties: 
                  name: 
                    type: "string"
                  description: 
                    type: "string"
                  country: 
                    required: 
                      - "id"
                      - "name"
                    properties: 
                      id: 
                        type: "string"
                      name: 
                        type: "string"
                    type: "object"
                  date: 
                    required: 
                      - "iso"
                      - "datetime"
                    properties: 
                      iso: 
                        type: "string"
                      datetime: 
                        required: 
                          - "year"
                          - "month"
                          - "day"
                        properties: 
                          year: 
                            type: "number"
                          month: 
                            type: "number"
                          day: 
                            type: "number"
                        type: "object"
                    type: "object"
                  type: 
                    type: "array"
                    items: 
                      type: "string"
                  primary_type: 
                    type: "string"
                  canonical_url: 
                    type: "string"
                  urlid: 
                    type: "string"
                  locations: 
                    type: "string"
                  states: 
                    type: "string"
          type: "object"

    MyHoliday:
      required:
        - "title"
        - "description"
        - "date"
      properties: 
        id: 
          type: "string"
          example: "ccdb65ce-baa7-4536-8315-c2e7ecb6bc6e"
        title: 
          type: "string"
          example: "New Year's day"
        description: 
          type: "string"
          example: "..."
        date: 
          type: "string"
          example: "2024.01.01"

  securitySchemes:
    CalendarificAPIKey:
      name: api_key
      type: apiKey
      in: query

    LookforwardAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://api.lookforward.test/auth
          tokenUrl: https://api.lookforward.test/token
          scopes:
            SyncHolidays: Synchronize user holiday list.

paths:
  /countries:
    servers:
      - url: https://calendarific.com/api/v2
    get:
      tags:
        - Calendarific
      description: Get list of supported countries.
      security:
        - CalendarificAPIKey: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CountryResponse"

  /holidays:
    servers:
      - url: https://calendarific.com/api/v2
    get:
      tags:
        - Calendarific
      description: Get a list of holidays.
      security:
        - CalendarificAPIKey: []
      parameters:
        - name: country
          in: query
          required: true
          description: Which country to get holidays for. This should be a supported country, specifies in ISO-3166 format.
          schema:
            type: string
          example: HU
        - name: year
          in: query
          required: true
          description: Get holidays for this year, up to 2049.
          schema:
            type: integer
          example: 2023
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HolidayResponse"

  /myholidays:
    post: 
      tags:
        - Lookforward
      description: Create a new holiday resource.
      security:
        - LookforwardAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MyHoliday"
      responses:
        '201':
          description: 'Created'
          headers:
            Location:
              schema:
                type: string
              description: URL of the created resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MyHoliday"
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

    get:
      tags:
        - Lookforward
      description: Get a list of every holiday resource.
      security:
        - LookforwardAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MyHoliday"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /myholidays/{id}:
    put:
      tags:
        - Lookforward
      description: Modify or create a new holiday resource with the specified id.
      security:
        - LookforwardAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the holiday resource to modify or create.
          schema:
            type: string
          example: ccdb65ce-baa7-4536-8315-c2e7ecb6bc6e
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MyHoliday"
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

    delete:
      tags:
        - Lookforward
      description: Delete the specified holiday resource.
      security:
        - LookforwardAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the holiday resource to delete.
          schema:
            type: string
          example: ccdb65ce-baa7-4536-8315-c2e7ecb6bc6e
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

    get:
      tags:
        - Lookforward
      description: Get details of a specific holiday resource.
      security:
        - LookforwardAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the holiday resource to get.
          schema:
            type: string
          example: ccdb65ce-baa7-4536-8315-c2e7ecb6bc6e
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MyHoliday"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
